# Generated by Django 3.2 on 2021-05-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
